---
- name: aide service
  become: yes
  become_method: sudo
  template:
    src: aidecheck.service.j2
    dest: /lib/systemd/system/aidecheck.service
    backup: yes
    mode: 0644
    owner: root
    group: root
  tags:
    - aide

- name: aide timer
  become: yes
  become_method: sudo
  template:
    src: aidecheck.timer.j2
    dest: /lib/systemd/system/aidecheck.timer
    backup: yes
    mode: 0644
    owner: root
    group: root
  notify:
    - reload systemd
    - enable aidecheck
    - start aidecheck
  tags:
    - aide
...
