---
- name: remove users
  become: yes
  become_method: sudo
  user:
    name: "{{ item }}"
    state: absent
    remove: yes
  with_items:
    - games
    - gnats
    - irc
    - list
    - news
    - uucp
  ignore_errors: yes
  tags:
    - users
...
