---
- name: apt update
  become: yes
  become_method: sudo
  apt:
    update_cache: yes
    cache_valid_time: 1800
  tags: apt

- name: apt upgrade
  become: yes
  become_method: sudo
  apt:
    upgrade: safe
  tags: apt

- name: disable net modules
  become: yes
  become_method: sudo
  template:
    src: disablenet.conf.j2
    dest: /etc/modprobe.d/disablenet.conf
    backup: yes
    mode: 0644
    owner: root
    group: root
  tags: modprobe

- name: disable file system modules
  become: yes
  become_method: sudo
  template:
    src: disablemnt.conf.j2
    dest: /etc/modprobe.d/disablemnt.conf
    backup: yes
    mode: 0644
    owner: root
    group: root
  tags: modprobe

- name: systemd system.conf
  become: yes
  become_method: sudo
  template:
    src: system.conf.j2
    dest: /etc/systemd/system.conf
    backup: yes
    mode: 0644
    owner: root
    group: root
  notify:
    - reload systemd
  tags: systemd

- name: systemd user.conf
  become: yes
  become_method: sudo
  template:
    src: user.conf.j2
    dest: /etc/systemd/user.conf
    backup: yes
    mode: 0644
    owner: root
    group: root
  notify:
    - reload systemd
  tags: systemd

- name: systemd journald.conf
  become: yes
  become_method: sudo
  template:
    src: journald.conf.j2
    dest: /etc/systemd/journald.conf
    backup: yes
    mode: 0644
    owner: root
    group: root
  notify:
    - reload systemd
  tags: systemd

- name: timesyncd.conf
  become: yes
  become_method: sudo
  template:
    src: timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    backup: yes
    mode: 0644
    owner: root
    group: root
  notify:
    - reload systemd
  tags: systemd

- name: hosts.allow
  become: yes
  become_method: sudo
  template:
    src: hosts.allow.j2
    dest: /etc/hosts.allow
    backup: yes
    mode: 0644
    owner: root
    group: root
  tags: hosts.allow

- name: hosts.deny
  become: yes
  become_method: sudo
  template:
    src: hosts.deny.j2
    dest: /etc/hosts.deny
    backup: yes
    mode: 0644
    owner: root
    group: root
  tags: hosts.deny

- name: login.defs
  become: yes
  become_method: sudo
  template:
    src: login.defs.j2
    dest: /etc/login.defs
    backup: yes
    mode: 0644
    owner: root
    group: root
  tags: login.defs

- name: sysctl
  become: yes
  become_method: sudo
  template:
    src: sysctl.conf.j2
    dest: /etc/sysctl.conf
    backup: yes
    mode: 0600
    owner: root
    group: root
  notify:
    - restart sysctl
  tags: sysctl

- name: limits.conf
  become: yes
  become_method: sudo
  template:
    src: limits.conf.j2
    dest: /etc/security/limits.conf
    backup: yes
    mode: 0644
    owner: root
    group: root
  tags: limits.conf

- name: package installation
  become: yes
  become_method: sudo
  apt:
    name: "{{ item }}"
    state: latest
    install_recommends: no
  with_items:
    - acct
    - aide-common
    - apparmor-profiles
    - apparmor-utils
    - auditd
    - haveged
    - libpam-cracklib
    - libpam-tmpdir
    - openssh-server
    - rkhunter
  tags: packages

- name: audit.rules
  become: yes
  become_method: sudo
  template:
    src: audit.rules.j2
    dest: /etc/audit/audit.rules
    backup: yes
    mode: 0600
    owner: root
    group: root
  notify:
      - restart auditd
  tags: audit.rules
...
