---
- name: apt update
  become: yes
  become_method: sudo
  apt:
    update_cache: yes
    cache_valid_time: 1800
  tags: apt

- name: apt upgrade
  become: yes
  become_method: sudo
  apt:
    upgrade: safe
  tags: apt

- name: sysctl
  become: yes
  become_method: sudo
  template:
    src: sysctl.conf
    dest: /etc/sysctl.conf
    backup: yes
    mode: 0600
    owner: root
    group: root
  notify:
        - restart sysctl
  tags: sysctl
...
