---
- name: restart docker
  become: yes
  become_method: sudo
  service: name=docker state=restarted

- name: reload systemd
  become: yes
  become_method: sudo
  command: systemctl daemon-reload
...
