---
- name: restart docker
  become: 'yes'
  become_method: sudo
  service:
    name: docker
    state: restarted
  tags:
    - docker

- name: reload systemd
  become: 'yes'
  become_method: sudo
  systemd:
    daemon_reload: 'yes'
  tags:
    - systemd

- name: restart auditd
  become: 'yes'
  become_method: sudo
  service:
    name: auditd
    state: restarted
  tags:
    - auditd

- name: generate auditd
  become: 'yes'
  become_method: sudo
  command: augenrules
  tags:
    - auditd
...
