---
- name: create privoxy directory
  become: yes
  become_method: sudo
  file:
    path: /etc/privoxy/
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - privoxy

- name: add privoxy config
  become: yes
  become_method: sudo
  template:
    src: privoxy.config.j2
    dest: /etc/privoxy/config
    mode: 0644
    owner: root
    group: root
  tags:
    - privoxy

- name: privoxy container
  docker:
    name: privoxy
    image: konstruktoid/privoxy
    command: --no-daemon --user privoxy /etc/privoxy/config
    state: reloaded
    ports:
    - "{{ privoxy_listen_address }}:{{ privoxy_port }}:{{ privoxy_port }}"
    cap_drop: all
    cap_add:
      - setgid
      - setuid
    volumes:
      - /etc/privoxy/config:/etc/privoxy/config:ro
    pull: always
    restart_policy: on-failure
    restart_policy_retry: 3
  tags:
    - docker_container
    - privoxy
...
