---
- name: allow haproxy traffic
  become: yes
  become_method: sudo
  ufw:
    rule: allow
    src: "{{ haproxy_client_net }}"
    port: "{{ haproxy_bind_port }}"
    proto: tcp
  tags:
    - ufw
    - haproxy
...
