---
- name: install python3-pip
  become: 'yes'
  become_method: sudo
  apt:
    name: python3-pip
    state: latest
    install_recommends: 'no'
  tags: python

- name: install python3-setuptools
  become: 'yes'
  become_method: sudo
  apt:
    name: python3-setuptools
    state: latest
    install_recommends: 'no'
  tags: python

- name: install python3 docker
  become: 'yes'
  become_method: sudo
  pip:
    name: docker
  tags:
    - docker
    - python
...
