---
- name: sysctl
  become: yes
  become_method: sudo
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
  tags:
    - sysctl

- name: docker systemd service
  become: yes
  become_method: sudo
  template:
    src: docker.service.j2
    dest: /lib/systemd/system/docker.service
    mode: 0644
    owner: root
    group: root
  notify:
    - reload systemd
    - restart docker
  tags:
    - docker

- name: docker running and enabled
  become: yes
  become_method: sudo
  service:
    name: docker
    state: running
    enabled: yes
  ignore_errors: yes
  tags:
    - docker
...
