---
- name: remove python-pip deb
  become: yes
  become_method: sudo
  apt:
    name: python-pip
    state: absent
  tags: python

- name: install python-setuptools
  become: yes
  become_method: sudo
  apt:
    name: python-setuptools
    state: latest
    install_recommends: no
  tags: python

- name: install python-pip
  become: yes
  become_method: sudo
  easy_install:
    name: pip
  tags:
    - python

- name: install docker-py
  easy_install:
    name: docker-py
  tags:
    - docker
    - python
...
