---
- name: allow haproxy traffic
  become: 'yes'
  become_method: sudo
  ufw:
    rule: allow
    src: "{{ item }}"
    port: "{{ haproxy_bind_port }}"
    proto: tcp
  with_items:
    - "{{ haproxy_client_net }}"
  tags:
    - ufw
    - haproxy
...
