---
- name: restart auditd
  become: yes
  become_method: sudo
  service:
    name: auditd
    state: restarted

- name: generate auditd
  become: yes
  become_method: sudo
  command: augenrules

- name: restart sysctl
  become: yes
  become_method: sudo
  service:
    name: systemd-sysctl
    state: restarted

- name: reload systemd
  become: yes
  become_method: sudo
  command: systemctl daemon-reload

- name: rkhunter propupd
  become: yes
  become_method: sudo
  command: rkhunter --propupd

- name: enable aidecheck
  become: yes
  become_method: sudo
  command: systemctl reenable aidecheck.timer

- name: start aidecheck
  become: yes
  become_method: sudo
  command: systemctl start aidecheck.timer

- name: disable aidecheck
  become: yes
  become_method: sudo
  command: systemctl disable aidecheck.timer

- name: mask aidecheck
  become: yes
  become_method: sudo
  command: systemctl mask aidecheck.timer
...
