---
- name: restart auditd
  become: yes
  become_method: sudo
  service:
    name: auditd
    state: restarted

- name: restart sysctl
  become: yes
  become_method: sudo
  service:
    name: systemd-sysctl
    state: restarted

- name: reload systemd
  become: yes
  become_method: sudo
  command: systemctl daemon-reload
...
